version: '3.9'
services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - '3000:3000'
    environment:
      - PRODUCER_HOST=producer-service
    depends_on:
      - producer-service

  producer-service:
    build:
      context: ./producer-service
    ports:
      - '3003:3003'
